{
  "assets": [
    {
      "id": "ASSET-001",
      "name": "Production Database Server",
      "ip": "10.0.0.5",
      "port": 5432,
      "business_criticality": "CRITICAL",
      "owner": "Data Infrastructure Team",
      "record_count": 10000000,
      "data_sensitivity": "HIGH",
      "business_segment": "Customer Data"
    },
    {
      "id": "ASSET-002",
      "name": "Public API Gateway",
      "ip": "10.0.0.10",
      "port": 443,
      "business_criticality": "HIGH",
      "owner": "Gateway Team",
      "record_count": 250000,
      "data_sensitivity": "MEDIUM",
      "business_segment": "API Operations"
    },
    {
      "id": "ASSET-003",
      "name": "Production Struts Gateway",
      "ip": "10.0.0.150",
      "port": 8080,
      "business_criticality": "CRITICAL",
      "owner": "Payments Team",
      "record_count": 5000000,
      "data_sensitivity": "HIGH",
      "business_segment": "Payments Gateway"
    },
    {
      "id": "ASSET-004",
      "name": "Customer Payment Database",
      "ip": "10.0.0.20",
      "port": 3306,
      "business_criticality": "CRITICAL",
      "owner": "Finance Team",
      "record_count": 8000000,
      "data_sensitivity": "HIGH",
      "business_segment": "Finance"
    },
    {
      "id": "ASSET-005",
      "name": "Authentication Service",
      "ip": "10.0.0.25",
      "port": 8443,
      "business_criticality": "CRITICAL",
      "owner": "Identity Team",
      "record_count": 12000000,
      "data_sensitivity": "HIGH",
      "business_segment": "Identity & Auth"
    },
    {
      "id": "ASSET-006",
      "name": "Employee HR Portal",
      "ip": "10.0.0.30",
      "port": 8444,
      "business_criticality": "HIGH",
      "owner": "HR Systems Team",
      "record_count": 5000,
      "data_sensitivity": "HIGH",
      "business_segment": "Human Resources"
    },
    {
      "id": "ASSET-007",
      "name": "Corporate Email Server",
      "ip": "10.0.0.35",
      "port": 25,
      "business_criticality": "HIGH",
      "owner": "Messaging Team",
      "record_count": 2000000,
      "data_sensitivity": "MEDIUM",
      "business_segment": "Communications"
    },
    {
      "id": "ASSET-008",
      "name": "Backup Storage Server",
      "ip": "10.0.0.40",
      "port": 9000,
      "business_criticality": "HIGH",
      "owner": "Infrastructure Team",
      "record_count": 15000000,
      "data_sensitivity": "HIGH",
      "business_segment": "Backups"
    },
    {
      "id": "ASSET-009",
      "name": "Logging and Monitoring Server",
      "ip": "10.0.0.45",
      "port": 9200,
      "business_criticality": "MEDIUM",
      "owner": "Observability Team",
      "record_count": 50000000,
      "data_sensitivity": "LOW",
      "business_segment": "Monitoring"
    },
    {
      "id": "ASSET-010",
      "name": "Customer Analytics Engine",
      "ip": "10.0.0.50",
      "port": 5601,
      "business_criticality": "MEDIUM",
      "owner": "Analytics Team",
      "record_count": 3000000,
      "data_sensitivity": "MEDIUM",
      "business_segment": "Analytics"
    },
    {
      "id": "ASSET-011",
      "name": "Document Management System",
      "ip": "10.0.0.55",
      "port": 8081,
      "business_criticality": "MEDIUM",
      "owner": "Operations Team",
      "record_count": 500000,
      "data_sensitivity": "MEDIUM",
      "business_segment": "Operations"
    },
    {
      "id": "ASSET-012",
      "name": "Internal Git Repository",
      "ip": "10.0.0.60",
      "port": 3000,
      "business_criticality": "HIGH",
      "owner": "Developer Platform Team",
      "record_count": 12000,
      "data_sensitivity": "HIGH",
      "business_segment": "Engineering"
    },
    {
      "id": "ASSET-013",
      "name": "Kubernetes Control Plane",
      "ip": "10.0.0.65",
      "port": 6443,
      "business_criticality": "CRITICAL",
      "owner": "Platform Engineering Team",
      "record_count": 50000,
      "data_sensitivity": "HIGH",
      "business_segment": "Infrastructure"
    },
    {
      "id": "ASSET-014",
      "name": "Customer Support Portal",
      "ip": "10.0.0.70",
      "port": 8088,
      "business_criticality": "MEDIUM",
      "owner": "Support Team",
      "record_count": 450000,
      "data_sensitivity": "MEDIUM",
      "business_segment": "Customer Support"
    },
    {
      "id": "ASSET-015",
      "name": "Disaster Recovery Server",
      "ip": "10.0.0.75",
      "port": 9443,
      "business_criticality": "CRITICAL",
      "owner": "Business Continuity Team",
      "record_count": 15000000,
      "data_sensitivity": "HIGH",
      "business_segment": "Disaster Recovery"
    },
    {
      "id": "ASSET-016",
      "name": "Production Kafka Cluster",
      "ip": "10.0.0.80",
      "port": 9092,
      "business_criticality": "HIGH",
      "owner": "Streaming Platform Team",
      "record_count": 5000000,
      "data_sensitivity": "MEDIUM",
      "business_segment": "Streaming"
    },
    {
      "id": "ASSET-017",
      "name": "Enterprise CRM Application",
      "ip": "10.0.0.81",
      "port": 443,
      "business_criticality": "HIGH",
      "owner": "Sales Operations Team",
      "record_count": 1500000,
      "data_sensitivity": "HIGH",
      "business_segment": "Sales"
    },
    {
      "id": "ASSET-018",
      "name": "Core ERP System",
      "ip": "10.0.0.82",
      "port": 8000,
      "business_criticality": "CRITICAL",
      "owner": "ERP Platform Team",
      "record_count": 8500000,
      "data_sensitivity": "HIGH",
      "business_segment": "ERP & Finance"
    },
    {
      "id": "ASSET-019",
      "name": "Billing Operations Service",
      "ip": "10.0.0.83",
      "port": 8082,
      "business_criticality": "CRITICAL",
      "owner": "Billing & Finance Team",
      "record_count": 4500000,
      "data_sensitivity": "HIGH",
      "business_segment": "Billing"
    },
    {
      "id": "ASSET-020",
      "name": "Customer Redis Cache",
      "ip": "10.0.0.84",
      "port": 6379,
      "business_criticality": "MEDIUM",
      "owner": "Caching Infrastructure Team",
      "record_count": 300000,
      "data_sensitivity": "MEDIUM",
      "business_segment": "Customer Portal"
    },
    {
      "id": "ASSET-021",
      "name": "RabbitMQ Message Broker",
      "ip": "10.0.0.85",
      "port": 5672,
      "business_criticality": "HIGH",
      "owner": "Middleware Team",
      "record_count": 1200000,
      "data_sensitivity": "LOW",
      "business_segment": "Messaging Queue"
    },
    {
      "id": "ASSET-022",
      "name": "Internal DNS Resolver",
      "ip": "10.0.0.86",
      "port": 53,
      "business_criticality": "CRITICAL",
      "owner": "Network Operations Team",
      "record_count": 10000,
      "data_sensitivity": "LOW",
      "business_segment": "Core Network"
    },
    {
      "id": "ASSET-023",
      "name": "Enterprise VPN Gateway",
      "ip": "10.0.0.87",
      "port": 1194,
      "business_criticality": "CRITICAL",
      "owner": "IT Security Team",
      "record_count": 5000,
      "data_sensitivity": "HIGH",
      "business_segment": "Remote Access"
    },
    {
      "id": "ASSET-024",
      "name": "SIEM Collector Node",
      "ip": "10.0.0.88",
      "port": 514,
      "business_criticality": "HIGH",
      "owner": "Security Operations Center",
      "record_count": 75000000,
      "data_sensitivity": "HIGH",
      "business_segment": "Security Operations"
    },
    {
      "id": "ASSET-025",
      "name": "Production Elasticsearch Cluster",
      "ip": "10.0.0.89",
      "port": 9200,
      "business_criticality": "HIGH",
      "owner": "Search Infrastructure Team",
      "record_count": 62000000,
      "data_sensitivity": "MEDIUM",
      "business_segment": "Log Search"
    },
    {
      "id": "ASSET-026",
      "name": "Prometheus Monitoring Server",
      "ip": "10.0.0.90",
      "port": 9090,
      "business_criticality": "MEDIUM",
      "owner": "Observability Team",
      "record_count": 45000000,
      "data_sensitivity": "LOW",
      "business_segment": "Monitoring"
    },
    {
      "id": "ASSET-027",
      "name": "Machine Learning Model Server",
      "ip": "10.0.0.91",
      "port": 8501,
      "business_criticality": "MEDIUM",
      "owner": "Data Science Team",
      "record_count": 50000,
      "data_sensitivity": "LOW",
      "business_segment": "ML Operations"
    },
    {
      "id": "ASSET-028",
      "name": "Object Storage MinIO",
      "ip": "10.0.0.92",
      "port": 9000,
      "business_criticality": "HIGH",
      "owner": "Storage Platform Team",
      "record_count": 22000000,
      "data_sensitivity": "HIGH",
      "business_segment": "Data Lake"
    },
    {
      "id": "ASSET-029",
      "name": "Secondary Backup Server",
      "ip": "10.0.0.93",
      "port": 873,
      "business_criticality": "HIGH",
      "owner": "Infrastructure Team",
      "record_count": 18000000,
      "data_sensitivity": "HIGH",
      "business_segment": "Backups"
    },
    {
      "id": "ASSET-030",
      "name": "Disaster Recovery Database Replica",
      "ip": "10.0.0.94",
      "port": 5432,
      "business_criticality": "CRITICAL",
      "owner": "Business Continuity Team",
      "record_count": 10000000,
      "data_sensitivity": "HIGH",
      "business_segment": "Disaster Recovery"
    },
    {
      "id": "ASSET-031",
      "name": "Enterprise Analytics Warehouse",
      "ip": "10.0.0.95",
      "port": 5439,
      "business_criticality": "HIGH",
      "owner": "Analytics Team",
      "record_count": 95000000,
      "data_sensitivity": "MEDIUM",
      "business_segment": "Business Intelligence"
    },
    {
      "id": "ASSET-032",
      "name": "HR Personnel Database",
      "ip": "10.0.0.96",
      "port": 3306,
      "business_criticality": "HIGH",
      "owner": "HR Systems Team",
      "record_count": 25000,
      "data_sensitivity": "HIGH",
      "business_segment": "Human Resources"
    },
    {
      "id": "ASSET-033",
      "name": "Corporate Finance App",
      "ip": "10.0.0.97",
      "port": 8080,
      "business_criticality": "CRITICAL",
      "owner": "Finance Systems Team",
      "record_count": 550000,
      "data_sensitivity": "HIGH",
      "business_segment": "Finance"
    },
    {
      "id": "ASSET-034",
      "name": "Main Customer Portal Web App",
      "ip": "10.0.0.98",
      "port": 443,
      "business_criticality": "HIGH",
      "owner": "Digital Experience Team",
      "record_count": 1200000,
      "data_sensitivity": "MEDIUM",
      "business_segment": "Customer Portal"
    },
    {
      "id": "ASSET-035",
      "name": "Stripe Payment Gateway Bridge",
      "ip": "10.0.0.99",
      "port": 8443,
      "business_criticality": "CRITICAL",
      "owner": "Payments Team",
      "record_count": 9000000,
      "data_sensitivity": "HIGH",
      "business_segment": "Payments Gateway"
    },
    {
      "id": "ASSET-036",
      "name": "Jenkins CI/CD Build Server",
      "ip": "10.0.0.100",
      "port": 8080,
      "business_criticality": "HIGH",
      "owner": "Developer Platform Team",
      "record_count": 65000,
      "data_sensitivity": "HIGH",
      "business_segment": "CI/CD Pipeline"
    },
    {
      "id": "ASSET-037",
      "name": "Internal Confluence Wiki",
      "ip": "10.0.0.101",
      "port": 8090,
      "business_criticality": "MEDIUM",
      "owner": "IT Support Team",
      "record_count": 150000,
      "data_sensitivity": "HIGH",
      "business_segment": "Knowledge Management"
    },
    {
      "id": "ASSET-038",
      "name": "Keycloak IAM Service",
      "ip": "10.0.0.102",
      "port": 8443,
      "business_criticality": "CRITICAL",
      "owner": "Identity Team",
      "record_count": 12500000,
      "data_sensitivity": "HIGH",
      "business_segment": "Identity & Auth"
    },
    {
      "id": "ASSET-039",
      "name": "Solr Search Cluster",
      "ip": "10.0.0.103",
      "port": 8983,
      "business_criticality": "MEDIUM",
      "owner": "Search Infrastructure Team",
      "record_count": 35000000,
      "data_sensitivity": "MEDIUM",
      "business_segment": "Product Search"
    },
    {
      "id": "ASSET-040",
      "name": "Snowflake Data Warehouse Sync Node",
      "ip": "10.0.0.104",
      "port": 443,
      "business_criticality": "HIGH",
      "owner": "Data Infrastructure Team",
      "record_count": 85000000,
      "data_sensitivity": "HIGH",
      "business_segment": "Analytics"
    },
    {
      "id": "ASSET-041",
      "name": "Memcached Cache Cluster",
      "ip": "10.0.0.105",
      "port": 11211,
      "business_criticality": "MEDIUM",
      "owner": "Caching Infrastructure Team",
      "record_count": 15000,
      "data_sensitivity": "LOW",
      "business_segment": "Session Cache"
    },
    {
      "id": "ASSET-042",
      "name": "Production API Gateway Edge",
      "ip": "10.0.0.106",
      "port": 443,
      "business_criticality": "HIGH",
      "owner": "Gateway Team",
      "record_count": 450000,
      "data_sensitivity": "MEDIUM",
      "business_segment": "API Operations"
    },
    {
      "id": "ASSET-043",
      "name": "S3 Backed Object Store",
      "ip": "10.0.0.107",
      "port": 9000,
      "business_criticality": "HIGH",
      "owner": "Storage Platform Team",
      "record_count": 50000000,
      "data_sensitivity": "HIGH",
      "business_segment": "Data Lake"
    },
    {
      "id": "ASSET-044",
      "name": "GitLab Code Repository Server",
      "ip": "10.0.0.108",
      "port": 22,
      "business_criticality": "HIGH",
      "owner": "Developer Platform Team",
      "record_count": 28000,
      "data_sensitivity": "HIGH",
      "business_segment": "Engineering"
    },
    {
      "id": "ASSET-045",
      "name": "Kubernetes Worker Node Pool",
      "ip": "10.0.0.109",
      "port": 10250,
      "business_criticality": "CRITICAL",
      "owner": "Platform Engineering Team",
      "record_count": 750000,
      "data_sensitivity": "MEDIUM",
      "business_segment": "Infrastructure"
    },
    {
      "id": "ASSET-046",
      "name": "Corporate Active Directory Domain Controller",
      "ip": "10.0.0.110",
      "port": 389,
      "business_criticality": "CRITICAL",
      "owner": "Identity Team",
      "record_count": 15000,
      "data_sensitivity": "HIGH",
      "business_segment": "Identity & Auth"
    },
    {
      "id": "ASSET-047",
      "name": "Customer Notification Kafka Topic",
      "ip": "10.0.0.111",
      "port": 9092,
      "business_criticality": "HIGH",
      "owner": "Streaming Platform Team",
      "record_count": 12000000,
      "data_sensitivity": "MEDIUM",
      "business_segment": "Streaming"
    },
    {
      "id": "ASSET-048",
      "name": "Logstash Processing Node",
      "ip": "10.0.0.112",
      "port": 5044,
      "business_criticality": "MEDIUM",
      "owner": "Observability Team",
      "record_count": 32000000,
      "data_sensitivity": "LOW",
      "business_segment": "Monitoring"
    },
    {
      "id": "ASSET-049",
      "name": "Production PostgreSQL Database Server",
      "ip": "10.0.0.113",
      "port": 5432,
      "business_criticality": "CRITICAL",
      "owner": "Data Infrastructure Team",
      "record_count": 40000000,
      "data_sensitivity": "HIGH",
      "business_segment": "Customer Data"
    },
    {
      "id": "ASSET-050",
      "name": "Marketing Mail Server",
      "ip": "10.0.0.114",
      "port": 25,
      "business_criticality": "MEDIUM",
      "owner": "Messaging Team",
      "record_count": 8000000,
      "data_sensitivity": "LOW",
      "business_segment": "Communications"
    },
    {
      "id": "ASSET-051",
      "name": "Legal Document Archival System",
      "ip": "10.0.0.115",
      "port": 8081,
      "business_criticality": "HIGH",
      "owner": "Operations Team",
      "record_count": 1100000,
      "data_sensitivity": "HIGH",
      "business_segment": "Operations"
    },
    {
      "id": "ASSET-052",
      "name": "Inventory Management ERP Module",
      "ip": "10.0.0.116",
      "port": 8000,
      "business_criticality": "HIGH",
      "owner": "ERP Platform Team",
      "record_count": 2400000,
      "data_sensitivity": "MEDIUM",
      "business_segment": "ERP & Finance"
    },
    {
      "id": "ASSET-053",
      "name": "Grafana Dashboards Server",
      "ip": "10.0.0.117",
      "port": 3000,
      "business_criticality": "MEDIUM",
      "owner": "Observability Team",
      "record_count": 2000,
      "data_sensitivity": "LOW",
      "business_segment": "Monitoring"
    },
    {
      "id": "ASSET-054",
      "name": "Enterprise Secret Vault (HashiCorp)",
      "ip": "10.0.0.118",
      "port": 8200,
      "business_criticality": "CRITICAL",
      "owner": "IT Security Team",
      "record_count": 150000,
      "data_sensitivity": "HIGH",
      "business_segment": "Security Operations"
    },
    {
      "id": "ASSET-055",
      "name": "Customer Billing DB Replica",
      "ip": "10.0.0.119",
      "port": 3306,
      "business_criticality": "CRITICAL",
      "owner": "Billing & Finance Team",
      "record_count": 4500000,
      "data_sensitivity": "HIGH",
      "business_segment": "Billing"
    },
    {
      "id": "ASSET-056",
      "name": "Product Catalog Redis Cache",
      "ip": "10.0.0.120",
      "port": 6379,
      "business_criticality": "HIGH",
      "owner": "Caching Infrastructure Team",
      "record_count": 800000,
      "data_sensitivity": "LOW",
      "business_segment": "Product Search"
    },
    {
      "id": "ASSET-057",
      "name": "Customer Feedback API Node",
      "ip": "10.0.0.121",
      "port": 8080,
      "business_criticality": "LOW",
      "owner": "Gateway Team",
      "record_count": 250000,
      "data_sensitivity": "MEDIUM",
      "business_segment": "API Operations"
    },
    {
      "id": "ASSET-058",
      "name": "Partner Integration Gateway",
      "ip": "10.0.0.122",
      "port": 443,
      "business_criticality": "HIGH",
      "owner": "Gateway Team",
      "record_count": 5000000,
      "data_sensitivity": "HIGH",
      "business_segment": "API Operations"
    },
    {
      "id": "ASSET-059",
      "name": "DevOps Ansible Control Server",
      "ip": "10.0.0.123",
      "port": 22,
      "business_criticality": "MEDIUM",
      "owner": "Developer Platform Team",
      "record_count": 5000,
      "data_sensitivity": "HIGH",
      "business_segment": "Engineering"
    },
    {
      "id": "ASSET-060",
      "name": "Business Intelligence Reporting Node",
      "ip": "10.0.0.124",
      "port": 8088,
      "business_criticality": "MEDIUM",
      "owner": "Analytics Team",
      "record_count": 12000000,
      "data_sensitivity": "MEDIUM",
      "business_segment": "Business Intelligence"
    }
  ]
}